 import {  Zap, Database, Gauge, Lock, Cpu, CloudCog, Activity, Layers, Trophy, Lightbulb, Sparkles, ArrowRight } from "lucide-react";
 const slides = [
  {
    title: "Increasing Backend Performance",
    subtitle: "Node.js • Express • MongoDB",
    description: "Master the art of building lightning-fast backend systems",
    bullets: [
      "What performance really means in production environments",
      "Real bottlenecks we face and how to identify them",
      "Building a team-level optimization mindset",
    ],
    icon: Zap,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#f97316",
    bgPattern: "dots",
  },
  {
    title: "What Is Backend Performance?",
    description: "Understanding the core metrics that matter",
    bullets: [
      "Response time (latency) - Speed matters to users",
      "Throughput (requests/sec) - Handling concurrent load",
      "CPU & memory usage - Resource optimization",
      "Scalability under load - Growing with demand",
    ],
    icon: Gauge,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#3b82f6",
    bgPattern: "dots",
  },
  {
    title: "Common Bottlenecks",
    description: "Identifying and eliminating performance killers",
    bullets: [
      "Slow or unindexed database queries",
      "Too many database calls per request (N+1 problem)",
      "Blocking the Node.js event loop",
      "Missing caching strategy",
      "Lack of monitoring and observability",
    ],
    icon: Lock,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#ef4444",
    bgPattern: "dots",
  },
  {
    title: "Database Optimization",
    subtitle: "MongoDB Best Practices",
    description: "Squeeze maximum performance from your database",
    bullets: [
      "Create indexes on frequently filtered fields",
      "Use projection to avoid returning full documents",
      "Implement pagination by default for all lists",
      "Use aggregation pipelines wisely for complex queries",
    ],
    icon: Database,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#22c55e",
    bgPattern: "dots",
  },
  {
    title: "Reduce Database Calls",
    description: "Minimize round trips to your database",
    bullets: [
      "Avoid N+1 queries with proper data loading",
      "Use populate() carefully - it's expensive",
      "Merge multiple queries when possible",
      "Cache frequently accessed data",
    ],
    icon: Layers,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#8b5cf6",
    bgPattern: "dots",
  },
  {
    title: "Caching with Redis",
    description: "Speed up read-heavy operations dramatically",
    bullets: [
      "Cache read-heavy endpoints and computations",
      "Store user profiles & permissions for quick access",
      "Cache configuration & lookup data",
      "Implement TTL-based cache invalidation strategy",
    ],
    icon: CloudCog,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#f97316",
    bgPattern: "dots",
  },
  {
    title: "Async & Non-Blocking Code",
    description: "Keep your event loop running smoothly",
    bullets: [
      "Node.js is single-threaded - respect the event loop",
      "Blocking code slows down all concurrent requests",
      "Use message queues & background jobs for heavy work",
      "Leverage worker threads for CPU-intensive tasks",
    ],
    icon: Cpu,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#06b6d4",
    bgPattern: "dots",
  },
  {
    title: "API Design Best Practices",
    subtitle: "Express.js Architecture",
    description: "Structure your code for maintainability and speed",
    bullets: [
      "Keep controllers thin - handle routing only",
      "Implement service layer for business logic",
      "Validate input early to fail fast",
      "Return smaller JSON responses - only what's needed",
    ],
    icon: Activity,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#84cc16",
    bgPattern: "dots",
  },
  {
    title: "Logging & Monitoring",
    description: "You can't optimize what you don't measure",
    bullets: [
      "Measure response time per route endpoint",
      "Log and alert on slow database queries",
      "Track event loop delay and lag metrics",
      "Use professional tools: PM2 • Pino • Grafana • Prometheus",
    ],
    icon: Activity,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#d946ef",
    bgPattern: "dots",
  },
  {
    title: "Real-World Impact",
    description: "See the dramatic difference optimization makes",
    bullets: [
      "Before optimization: 5 database calls → 1200ms response",
      "After optimization: 1 database call + Redis → 120ms",
      "10x performance improvement with same codebase",
    ],
    icon: Trophy,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#eab308",
    bgPattern: "dots",
  },
  {
    title: "Key Takeaways",
    description: "Remember these core principles",
    bullets: [
      "Database optimization delivers the biggest performance wins",
      "Cache aggressively, but invalidate safely",
      "Never block the event loop - keep it responsive",
      "Performance is a team habit, not a one-time fix",
    ],
    icon: Lightbulb,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#10b981",
    bgPattern: "dots",
  },
  {
    title: "Thank You!",
    subtitle: "Questions & Discussion",
    description: "Let's build faster, more efficient systems together",
    bullets: [
      "Presented by: Mazen Elwany",
      "Remember: Performance is a journey, not a destination",
      "Start optimizing one bottleneck at a time",
    ],
    icon: Sparkles,
    gradient: "from-slate-900 via-slate-800 to-slate-900",
    accentColor: "#a855f7",
    bgPattern: "dots",
    isThankYou: true,
  },
];
export default slides